export const NUM_HOLES = 16;
export const MOLE_TYPES = {
  MOLE: 'MOLE',
  STAR: 'STAR',
  BOMB: 'BOMB',
  GRAPE: 'GRAPE',
  BLUEBERRY: 'BLUEBERRY',
  LEMON: 'LEMON',
  THUMBS_DOWN: 'THUMBS_DOWN',
  BANANA: 'BANANA',
};
